config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "andrew", password: "admin", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="editorListTitle">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div class="editorListBody">
    <%= form.label :text %><br>
    <%= form.text_area :text, :class => "tinymce", :rows => 10, :cols => 12 %>
    <%= tinymce %>
  </div>

  <div class="formSubmitButton">
    <%= form.submit "Save List" %>
    <%= link_to 'Cancel', root_path %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <div class="whiteHeader row">
      <h2 class="headerLabelSmall col">Edit To Do List</h2>
      <h1 class="col titleLabel"><%= link_to 'Blu-to-do', root_path %></h1>
    </div>
    <div class="gradientBackground">

      <%= render 'form' %>

      <%= link_to 'Back', root_path %>
    </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="whiteHeader row">
      <h1 class="headerLabel col">
           <%= link_to new_article_path do %>
              <%= image_tag "addIcon.svg", class: "iconSmall adjustIconUp" %>
            New List
        </h1>
        <% end %>
      <h1 class="col titleLabel">Blu-to-do</h1>
    </div>
    <div class="scrollView row flex-row flex-nowrap">
        <% @articles.each do |article| %>
          <div class="whiteList col">
            <div class="row listHeader">
              <div class="col-xs">
                <%= link_to edit_article_path(article) do %>
                 <%= image_tag "editIcon.svg", class: "iconNormal adjustIconDown" %>
                <% end %>
              </div>
              <div class="col centerTitle">
                <h1 class="listTitle"><%= article.title %></h1>
              </div>
              <div class="col-xs">
                <%= link_to article_path(article),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } do %>
                 <%= image_tag "deleteIcon.svg", class: "iconNormal adjustIconDown" %>
                <% end %>
              </div>
            </div>
            <div class="row">
              <div class="listBody"><%= article.text.html_safe %></div>
            </div>
          </div>
        <% end %>
        <div class="endSpacer">
          <p></p>
        </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="whiteHeader row">
      <h2 class="headerLabelSmall col">New To Do List</h2>
      <h1 class="col titleLabel"><%= link_to 'Blu-to-do', root_path %></h1>
    </div>
    <div class="gradientBackground">

      <%= render 'form' %>

      <%= link_to 'Back', root_path %>
    </div>
</div>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text.html_safe %>
</p>

<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blu-to-do</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My To do\'s', controller: 'articles' %>